# Generated by Django 2.1 on 2021-03-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_rescontent_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rescontent',
            options={'verbose_name': '资源', 'verbose_name_plural': '资源'},
        ),
    ]
