# Generated by Django 2.1 on 2021-03-01 11:09

import ckeditor.fields
import courses.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True, verbose_name='显示')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='链接')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键字')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('order', courses.fields.OrderField(blank=True, verbose_name='排序')),
                ('md_content', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='内容')),
                ('html_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='内容')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_related', to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '博客内容',
                'verbose_name_plural': '博客内容',
            },
        ),
    ]
