# Generated by Django 2.1 on 2021-03-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcontent',
            options={'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
    ]
